SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[uy] (
		[col1]     [int] NULL,
		[col2]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[uy] SET (LOCK_ESCALATION = TABLE)
GO
